### ISSUE TITLE
More secure approach for fetching collector builder

### ISSUE THREAD

**Issue by punya** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#13]
(h/t @jsuereth for flagging this and @braydonk for suggesting a solution.)

In https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/blob/5c348ef9765497565e4f51abe96b2d3de04f037f/Makefile#L26 we download the `ocb` binary without verifying its integrity. This leaves us vulnerable to MITM attacks.

Can we switch to a more secure approach such as

* verifying a content hash
* using `go install` (possibly with a saved go.mod)

?

**Comment by damemi** [comment]
Updated to use `go install` in https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/pull/12
