### ISSUE TITLE
Demonstrate how to run the collector with/without without workload identity

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#14]
Forked from https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/pull/11#discussion_r956292055

It needs to be clear when WI steps are required or not.

**Comment by aabmass** [comment]
Triaged, this is low priority

**Comment by damemi** [comment]
This is pretty well documented in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/main/exporter/collector#prerequisite-authenticating (and in collector-contrib). It's also not really a builder-specific sample, more of a general docs topic. Closing this
