### ISSUE TITLE
Add toc-generation presubmit + check

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#18]
Forked from https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/pull/17#discussion_r976668182

> it would look nice to have sub-bullets for each recipe up here in the ToC

> I used a [toc generator](https://github.com/ekalinin/github-markdown-toc) for this. maybe we should add that to the repo/precommit

**Comment by aabmass** [comment]
@damemi working on this
