### ISSUE TITLE
Please document the purpose of each exposed port

### ISSUE THREAD

**Issue by punya** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#2]
https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/blob/6e32e88a8846c15feeefbbac932f690430f42b55/Dockerfile#L22

**Comment by damemi** [comment]
I actually got these from the friction log, so we should look more at them (and maybe allow them to be customized?)
`4317` - default [otlp](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md#getting-started) receiver
`55678` - [opencensus](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md#opencensus-protocol) receiver
`55679` - [zpages](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#zpages)

**Comment by punya** [comment]
Can we add this info to the Dockerfile as a comment? I'm not sure if offering customization is worthwhile.
