### ISSUE TITLE
Version inconsistency

### ISSUE THREAD

**Issue by punya** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#3]
The Makefile mentions version v0.57.0

https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/blob/6e32e88a8846c15feeefbbac932f690430f42b55/Makefile#L16

but the builder config uses version v0.57.2

https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/blob/6e32e88a8846c15feeefbbac932f690430f42b55/builder-config.yaml#L17

Could we make these consistent, and improve our tooling to help keep them consistent over time?

**Comment by damemi** [comment]
This was a mistake on my end, v0.57.0 and .1 were skipped (retracted?) upstream.

As for improving tooling, we could probably create a single version source. But it might be good enough to just keep a regular release cadence consistent with upstream (though that is a lot of work for what this repo is meant to accomplish)
