### ISSUE TITLE
Should we include a Prometheus receiver?

### ISSUE THREAD

**Issue by punya** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#4]
We currently include the GMP exporter, which most people will want to use in concert with the Prometheus receiver.

**Comment by damemi** [comment]
I actually thought about it, but then just cut down the default list to just the Google-specific receivers and exporters (for at least the initial commits). I think we should definitely consider adding other receivers, like Prometheus especially for its use case

**Comment by dashpole** [comment]
A prometheus receiver is needed to support self-observability metrics, so I would recommend including it.

**Comment by punya** [comment]
From a user's perspective, I don't see the point of including a GMP exporter without a Prometheus receiver.
