### ISSUE TITLE
Error: "transport: authentication handshake failed" 

### ISSUE THREAD

**Issue by bhanupratapm02** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#50]
Trying to setup OTel Contrib on a on-prem server but seeing below error.  Any insights why this is failing is really helpfull. This is failing only in set of servers.  I compared the config file working vs non-working everything remains the same. 

I even tried with 0.86.0 version still failing.

otelcol-contrib: 2024-02-12T11:53:19.898-0500#011warn#011zapgrpc/zapgrpc.go:195#011[core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "monitoring.googleapis.com:443", ServerName: "monitoring.googleapis.com:443", }. Err: connection error: desc = "transport: authentication handshake failed: read tcp xxx.xxx.xx.xx:48498->xxx.xxx.xx.xx:443: read: connection reset by peer"#011{"grpc_log": true}

cat otelcol-contrib.service
[Unit]
Description=OpenTelemetry Collector Contrib
After=network.target

[Service]
EnvironmentFile=/etc/otelcol-contrib/otelcol-contrib.conf
ExecStart=/usr/bin/otelcol-contrib $OTELCOL_OPTIONS
KillMode=mixed
Restart=on-failure
Type=simple
User=otelcol-contrib
Group=otelcol-contrib

[Install]
WantedBy=multi-user.target

****
cat /etc/otelcol-contrib/otelcol-contrib.conf
# Systemd environment file for the otelcol-contrib service

# Command-line options for the otelcol-contrib service.
# Run `/usr/bin/otelcol-contrib --help` to see all available options.
OTELCOL_OPTIONS="--config=/etc/otelcol-contrib/config.yaml"
GOOGLE_APPLICATION_CREDENTIALS=/etc/otelcol-contrib/sa_key.json
http_proxy: "http://proxyserver:9090"
https_proxy: "http://proxyserver:9090"
no_proxy: "*.com,localhost"

cat /etc/otelcol-contrib/config.yaml
receivers:
  prometheus:
     config:
       scrape_configs:
         - job_name: 'elasticsearch'
           scrape_interval: 120s
           metrics_path: "/_prometheus/metrics"
           params:
           basic_auth:
             username: es_admin
             password_file: '/etc/config/secrets.txt'
           static_configs:
             - targets: ['localhost:9200']
               labels:
                 component: "elastic"
    

processors:
  resource/add_location:
    attributes:
    - key: "location"
      value: "us-east1"
      action: upsert

exporters:
  googlemanagedprometheus:

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [resource/add_location]
      exporters: [googlemanagedprometheus]

**Comment by damemi** [comment]
Hi @bhanupratapm02, could you try running the same config and setup with the latest upstream collector-contrib image from https://github.com/open-telemetry/opentelemetry-collector-contrib?

From the error I'm wondering if it could be related to your proxy, but I'm not sure. I'd also want to double check that you are authenticating correctly on all of your servers following the steps in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudexporter#prerequisite-authenticating

**Comment by bhanupratapm02** [comment]
Hi @damemi, Thank You for your insight.  I updated the image and yes proxy settings were wrong and in addition observed lot of drift in the server time.   I corrected proxy variables, server time and then started seeing metrics in grafana.
