### ISSUE TITLE
Docs: Pre-work

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#9]
The readme should include pre-work needed before the commands will work.  Steps should ideally link out to GCP docs.  Things that come to mind:

* Having a GCP project w/ billing
* Enabling the required APIs
* Having docker and gcloud installed

**Comment by psx95** [comment]
With the recent changes to [setup.md](https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/blob/main/deploy/gke/setup.md), could this issue be considered resolved ?
